import { _techStackValues } from "./types";

export const stackData: _techStackValues = {
  languages: [
    "JavaScript",
    "Python",
    "Golang",
    "Java",
    "C++",
    "C Sharp",
    "Rust",
    "PHP",
    "Swift",
    "TypeScript",
  ],
  databases: [
    "Postgres",
    "Firestore",
    "Mongodb",
    "MySQL",
    "Microsoft SQL Server",
    "Redis",
    "Elasticsearch",
    "Sqllite",
  ],
  clouds: [
    "AWS",
    "Google Cloud",
    "Microsoft Azure",
    "IBM Cloud",
    "Oracle",
    "Digital Ocean",
  ],
  apis: [
    "Stripe",
    "Spotify",
    "Twitter",
    "OpenWeatherMap",
    "Google Maps",
    "Slack",
    "PayPal",
    "Twilio",
    "DocuSign",
    "Facebook",
  ],
  frameworks: [
    "Nextjs",
    "Angular",
    "React",
    "Ruby on Rails",
    "Vue",
    "ASP.NET Core",
    "Django",
    "Express",
    "Spring",
  ],
};
